baseURL = "/"
languageCode = "en-us"
title = "Bryanthorton.com"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Alexis Collado, UX Designer"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "horton.bryant@gmail.com"
    facebook = "bryant.horton"
    twitter = "BryantHorton6"
    linkedin = "https://www.linkedin.com/in/bryant-horton-1c873/"
    
[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hello I'm Bryant a Radar Maintenance Technician"
    hero_right = ["**Currently working as a Military Training Leader**", "My passion for troubleshooting small and large voltage electronics makes me a strong addition to your team. During my first 4 years as a Radar Technician. I was able to repair a 5-million-dollar radar that was on its way to depot. Someone in my chain of command trusted my aptitude on the equipment and allowed me to troubleshoot the radar while it was in transit to depot. Within a week, I was able to find and solve the problem. There was a deflector in the sulfur hexafluoride (SF6) tank that was put on backwards from depot. This allowed -117 thousand kilovolts to ground out to the deflector instead of through the deflector. This accomplishment saved the Air Force 2 million dollars in repair costs. As a Radar Technician, I am mindful of the Air Force’s budget and deliberately provide maintenance with thought of keeping costs down for the Air Force. I understand the Radar theory, which allows me to troubleshoot problems further down to the component level. This allows for on the spot corrections and save funds in sending the component off for maintenance or sending a team in for a fix action. My focus as a Radar Technician is to forever be a student to the equipment. I am always learning, and I have a willingness to continue the learning process.  A hobby of mine is to continually learn about the advancement in current Radio Frequency technologies. How new technologies will affect my career field and how I can make job better/faster/efficient with these new technologies. I have had many accolades in my career in the Radar Technician career field. I have coined by the commander of the 455 communications squadron in Bagram, Afghanistan for my keen attention to detail. I was able to repair a 144 strand fiber run that was decimated by a mortar. I was again coined by the communications commander at Dover, Delaware for repairing 500 server related trouble tickets. Additionally, while repairing the trouble tickets I found a faulty fiber connection, once repaired this allowed servicemembers to dial 911 and the emergency management team would be able to locate the servicemember geographically."]
    resume = "ResumeCollado.pdf"

[params.process]
    enable = true
    title = "Work History"
    subtitle = "Skills"

[params.case_studies]
    enable = true
    title = "Hobbies"
    subtitle = "Conservation"

[params.footer]
    enable = false
